# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ManyToManyField(related_name='carted', to='login_app.User')),
                ('reviews', models.ManyToManyField(related_name='reviews', to='login_app.User')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
                ('product', models.ManyToManyField(related_name='product', to='commerce.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='joiners',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
