# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20170727_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='http://polyureashop.studio.crasman.fi/pub/web/img/no-image.jpg', max_length=500),
        ),
    ]
