# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_product_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.URLField(default='http://polyureashop.studio.crasman.fi/pub/web/img/no-image.jpg', max_length=500),
        ),
    ]
