# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20170727_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
